name: CloudnodeMSG
version: '${project.version}'
main: pro.cloudnode.smp.cloudnodemsg.CloudnodeMSG
api-version: '1.20'
author: Cloudnode
commands:
    message:
        description: Send a private message
        usage: /<command> <player> <message>
        aliases: [ "msg", "tell", "t", "whisper", "dm", "m", "pm" ]
    reply:
        description: Reply to a private message
        usage: /<command> <message>
        aliases: [ "r", "re" ]
    cloudnodemsg:
        description: CloudnodeMSG
        usage: /<command>
    ignore:
        description: Ignore a player
        usage: /<command> <player>
        aliases: [ "block" ]
    unignore:
        description: Unignore a player
        usage: /<command> <player>
        aliases: [ "unblock" ]
    togglemsg:
        description: Toggles private messages from a player
        usage: /<command> <player>
        aliases: [ "toggledms", "togglepms" ]
