name: CloudnodeMSG
version: '${project.version}'
main: pro.cloudnode.smp.cloudnodemsg.CloudnodeMSG
api-version: '1.20'
author: Cloudnode
softdepend:
  - PlaceholderAPI
commands:
    message:
        description: Send a private message
        usage: /<command> <player> [message]
        aliases: [ "msg", "tell", "t", "whisper", "dm", "m", "pm" ]
        permission: cloudnodemsg.use
    reply:
        description: Privately reply to the last message your received
        usage: /<command> <message>
        aliases: [ "r", "re" ]
        permission: cloudnodemsg.use
    cloudnodemsg:
        description: CloudnodeMSG
        usage: /<command>
    ignore:
        description: Ignore a player
        usage: /<command> <player>
        aliases: [ "block" ]
        permission: cloudnodemsg.ignore
    unignore:
        description: Unignore a player
        usage: /<command> <player>
        aliases: [ "unblock" ]
        permission: cloudnodemsg.ignore
    togglemsg:
        description: Toggle receiving private messages
        usage: /<command> [player]
        aliases: [ "toggledms", "togglepms" ]
        permission: cloudnodemsg.toggle
    teammsg:
        description: Send a private message to your teammates
        usage: /<command> [message]
        aliases: [ "tmsg", "teamchat" , "tm" ]
        permission: cloudnodemsg.use.team
